In [7]:
edges = [(0,1) , (0,4) , (1,2), (2,0) ,
(3,4) , (3,6), (4,0),(4,3),
(4,7) , (5,3), (5,7),
(6,5) , (7,4) , (7,8) ,
(8,5) , (8,9) , (9,8)]
import numpy as np

A= np.zeros(shape=(10,10))
for (i,j) in edges:
    A[i,j] = 1
print(A)

[[0. 1. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


In [12]:
import numpy as np
def neighbours (AMat, i):
    nbrs =[]
    (rows, cols) = AMat. shape
    for j in range(cols):
         if AMat [i, j]==1:

                nbrs. append (j)
    return(nbrs)
edges = [(0,1) , (0,4) , (1,2), (2,0) ,
(3,4) , (3,6), (4,0),(4,3),
(4,7) , (5,3), (5,7),
(6,5) , (7,4) , (7,8) ,
(8,5) , (8,9) , (9,8)]


A= np.zeros(shape=(10,10))
for (i,j) in edges:
    print("before ","(i,j)=",(i,j),"A[i,j]=",A[i,j])
    #print(type((i,j)))
    print(i,j)
    A[i,j] = 1
    print("after ",(i,j),A[i,j])
print(A)
neighbours (A,7)


before  (i,j)= (0, 1) A[i,j]= 0.0
0 1
after  (0, 1) 1.0
before  (i,j)= (0, 4) A[i,j]= 0.0
0 4
after  (0, 4) 1.0
before  (i,j)= (1, 2) A[i,j]= 0.0
1 2
after  (1, 2) 1.0
before  (i,j)= (2, 0) A[i,j]= 0.0
2 0
after  (2, 0) 1.0
before  (i,j)= (3, 4) A[i,j]= 0.0
3 4
after  (3, 4) 1.0
before  (i,j)= (3, 6) A[i,j]= 0.0
3 6
after  (3, 6) 1.0
before  (i,j)= (4, 0) A[i,j]= 0.0
4 0
after  (4, 0) 1.0
before  (i,j)= (4, 3) A[i,j]= 0.0
4 3
after  (4, 3) 1.0
before  (i,j)= (4, 7) A[i,j]= 0.0
4 7
after  (4, 7) 1.0
before  (i,j)= (5, 3) A[i,j]= 0.0
5 3
after  (5, 3) 1.0
before  (i,j)= (5, 7) A[i,j]= 0.0
5 7
after  (5, 7) 1.0
before  (i,j)= (6, 5) A[i,j]= 0.0
6 5
after  (6, 5) 1.0
before  (i,j)= (7, 4) A[i,j]= 0.0
7 4
after  (7, 4) 1.0
before  (i,j)= (7, 8) A[i,j]= 0.0
7 8
after  (7, 8) 1.0
before  (i,j)= (8, 5) A[i,j]= 0.0
8 5
after  (8, 5) 1.0
before  (i,j)= (8, 9) A[i,j]= 0.0
8 9
after  (8, 9) 1.0
before  (i,j)= (9, 8) A[i,j]= 0.0
9 8
after  (9, 8) 1.0
[[0. 1. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0

[4, 8]